name: Publish
description: Builds, captures, and publishes the compiled jar

inputs:
  version_modifier:
    description: Version Suffix
    required: false
    default: ''
  version_type:
    description: Version typee
    required: false
    default: release
  changelog:
    description: Changelog
    required: false
    default: ''
  modrinth_token:
    description: Modrinth Token
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Build
      uses: ./.github/actions/build
    - name: Upload to Modrinth
      run: ./gradlew modrinth
      shell: bash
      env:
        MODRINTH_CHANGELOG: ${{ inputs.changelog }}
        MODRINTH_TOKEN: ${{ inputs.modrinth_token }}
        MODRINTH_VERSION_MODIFIER: ${{ inputs.version_modifier }}
        MODRINTH_VERSION_TYPE: ${{ inputs.version_type }}
