name: Build
description: Builds the sources and captures the compile jar

inputs:
  capture-artifacts:
    description: Should artifacts be captured
    required: false
    default: true

runs:
  using: composite
  steps:
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Set-up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Make Gradle wrapper executable
      if: ${{ runner.os != 'Windows' }}
      run: chmod +x ./gradlew
    - name: Build
      run: ./gradlew build
    - name: Capture build artifacts
      if: ${{ inputs.capture-artifacts }}
      uses: actions/upload-artifact@v3
      with:
        name: Artifacts
        path: build/libs/
