name: Manual upload
on:
  workflow_dispatch:
    inputs:
      version_modifier:
        description: Version Suffix
        required: false
        default: ''
        type: string
      version_type:
        description: Version type
        required: false
        default: release
        type: choice
        options:
          - release
          - beta
          - alpha
      changelog:
        description: Changelog
        required: false
        default: ''
        type: string

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Publish
        uses: ./.github/actions/publish
        with:
          changelog: ${{ inputs.changelog }}
          version_modifier: ${{ inputs.version_modifier }}
          version_type: ${{ inputs.version_type }}
