name: Nightly build
on:
  schedule:
    - cron: 00 00 * * *

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Publish
        uses: ./.github/actions/publish
        with:
          changelog: Nightly build of `${{ env.GITHUB_REF }}`. View at https://github.com/acodili-jg/still-clouds/tree/${{ env.GITHUB_SHA }}
          modrinth_token: ${{ secrets.MODRINTH_TOKEN }}
          version_modifier: -nightly${{ env.GITHUB_SHA }}
          version_type: alpha
