name: Nightly build
on:
  schedule:
    - cron: 00 00 * * *

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build and capture artifacts
        uses: ./.github/actions/build
